# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp_memory/proto/memory.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mcp_memory/proto/memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmcp_memory/proto/memory.proto\x12\tmemory.v1\"Z\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttool_name\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"_\n\rIngestRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12$\n\x08messages\x18\x03 \x03(\x0b\x32\x12.memory.v1.Message\"\x1f\n\x0bIngestReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"A\n\x10GetMemoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"%\n\x0eGetMemoryReply\x12\x13\n\x0bmemory_text\x18\x01 \x01(\t\"C\n\x0e\x45nabledRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x07\x65nabled\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\n\n\x08_enabled\"\x1f\n\x0c\x45nabledReply\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"A\n\x0c\x44reamRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x07\x65nabled\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\n\n\x08_enabled\"\x1d\n\nDreamReply\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x1f\n\x0cResetRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x1d\n\nResetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc8\x02\n\x06Memory\x12\x42\n\x0eIngestMessages\x12\x18.memory.v1.IngestRequest\x1a\x16.memory.v1.IngestReply\x12\x43\n\tGetMemory\x12\x1b.memory.v1.GetMemoryRequest\x1a\x19.memory.v1.GetMemoryReply\x12=\n\x07\x45nabled\x12\x19.memory.v1.EnabledRequest\x1a\x17.memory.v1.EnabledReply\x12\x37\n\x05\x44ream\x12\x17.memory.v1.DreamRequest\x1a\x15.memory.v1.DreamReply\x12=\n\x0bResetMemory\x12\x17.memory.v1.ResetRequest\x1a\x15.memory.v1.ResetReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_memory.proto.memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=44
  _globals['_MESSAGE']._serialized_end=134
  _globals['_INGESTREQUEST']._serialized_start=136
  _globals['_INGESTREQUEST']._serialized_end=231
  _globals['_INGESTREPLY']._serialized_start=233
  _globals['_INGESTREPLY']._serialized_end=264
  _globals['_GETMEMORYREQUEST']._serialized_start=266
  _globals['_GETMEMORYREQUEST']._serialized_end=331
  _globals['_GETMEMORYREPLY']._serialized_start=333
  _globals['_GETMEMORYREPLY']._serialized_end=370
  _globals['_ENABLEDREQUEST']._serialized_start=372
  _globals['_ENABLEDREQUEST']._serialized_end=439
  _globals['_ENABLEDREPLY']._serialized_start=441
  _globals['_ENABLEDREPLY']._serialized_end=472
  _globals['_DREAMREQUEST']._serialized_start=474
  _globals['_DREAMREQUEST']._serialized_end=539
  _globals['_DREAMREPLY']._serialized_start=541
  _globals['_DREAMREPLY']._serialized_end=570
  _globals['_RESETREQUEST']._serialized_start=572
  _globals['_RESETREQUEST']._serialized_end=603
  _globals['_RESETREPLY']._serialized_start=605
  _globals['_RESETREPLY']._serialized_end=634
  _globals['_MEMORY']._serialized_start=637
  _globals['_MEMORY']._serialized_end=965
# @@protoc_insertion_point(module_scope)
