# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memory.proto import memory_pb2 as mcp__memory_dot_proto_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_memory/proto/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestMessages = channel.unary_unary(
                '/memory.v1.Memory/IngestMessages',
                request_serializer=mcp__memory_dot_proto_dot_memory__pb2.IngestRequest.SerializeToString,
                response_deserializer=mcp__memory_dot_proto_dot_memory__pb2.IngestReply.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/memory.v1.Memory/GetMemory',
                request_serializer=mcp__memory_dot_proto_dot_memory__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=mcp__memory_dot_proto_dot_memory__pb2.GetMemoryReply.FromString,
                _registered_method=True)
        self.Enabled = channel.unary_unary(
                '/memory.v1.Memory/Enabled',
                request_serializer=mcp__memory_dot_proto_dot_memory__pb2.EnabledRequest.SerializeToString,
                response_deserializer=mcp__memory_dot_proto_dot_memory__pb2.EnabledReply.FromString,
                _registered_method=True)
        self.Dream = channel.unary_unary(
                '/memory.v1.Memory/Dream',
                request_serializer=mcp__memory_dot_proto_dot_memory__pb2.DreamRequest.SerializeToString,
                response_deserializer=mcp__memory_dot_proto_dot_memory__pb2.DreamReply.FromString,
                _registered_method=True)
        self.ResetMemory = channel.unary_unary(
                '/memory.v1.Memory/ResetMemory',
                request_serializer=mcp__memory_dot_proto_dot_memory__pb2.ResetRequest.SerializeToString,
                response_deserializer=mcp__memory_dot_proto_dot_memory__pb2.ResetReply.FromString,
                _registered_method=True)


class MemoryServicer:
    """Missing associated documentation comment in .proto file."""

    def IngestMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMessages,
                    request_deserializer=mcp__memory_dot_proto_dot_memory__pb2.IngestRequest.FromString,
                    response_serializer=mcp__memory_dot_proto_dot_memory__pb2.IngestReply.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=mcp__memory_dot_proto_dot_memory__pb2.GetMemoryRequest.FromString,
                    response_serializer=mcp__memory_dot_proto_dot_memory__pb2.GetMemoryReply.SerializeToString,
            ),
            'Enabled': grpc.unary_unary_rpc_method_handler(
                    servicer.Enabled,
                    request_deserializer=mcp__memory_dot_proto_dot_memory__pb2.EnabledRequest.FromString,
                    response_serializer=mcp__memory_dot_proto_dot_memory__pb2.EnabledReply.SerializeToString,
            ),
            'Dream': grpc.unary_unary_rpc_method_handler(
                    servicer.Dream,
                    request_deserializer=mcp__memory_dot_proto_dot_memory__pb2.DreamRequest.FromString,
                    response_serializer=mcp__memory_dot_proto_dot_memory__pb2.DreamReply.SerializeToString,
            ),
            'ResetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetMemory,
                    request_deserializer=mcp__memory_dot_proto_dot_memory__pb2.ResetRequest.FromString,
                    response_serializer=mcp__memory_dot_proto_dot_memory__pb2.ResetReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.Memory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.Memory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Memory:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/IngestMessages',
            mcp__memory_dot_proto_dot_memory__pb2.IngestRequest.SerializeToString,
            mcp__memory_dot_proto_dot_memory__pb2.IngestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/GetMemory',
            mcp__memory_dot_proto_dot_memory__pb2.GetMemoryRequest.SerializeToString,
            mcp__memory_dot_proto_dot_memory__pb2.GetMemoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/Enabled',
            mcp__memory_dot_proto_dot_memory__pb2.EnabledRequest.SerializeToString,
            mcp__memory_dot_proto_dot_memory__pb2.EnabledReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/Dream',
            mcp__memory_dot_proto_dot_memory__pb2.DreamRequest.SerializeToString,
            mcp__memory_dot_proto_dot_memory__pb2.DreamReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/ResetMemory',
            mcp__memory_dot_proto_dot_memory__pb2.ResetRequest.SerializeToString,
            mcp__memory_dot_proto_dot_memory__pb2.ResetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
